### ISSUE TITLE
Discuss DB schema for Phase 1

### ISSUE THREAD

**Issue by youmustgo** [MIC-TEAM/miccha-design2#3]

**Comment by youmustgo** [comment]
## `movie`
|id|title|description|rating|duration|thumbnail|year|country|
|---|---|---|---|---|---|---|---|
|tt0088678|The Adventures of Mark Twain|Tom Sawyer, Becky Thatch…to meet Halley's Comet.|`G`|5160|https://ia.media-imdb.com/images/M/MV5BMTgyMTU5NjI4OF5BMl5BanBnXkFtZTcwNDU0NzA3OA@@._V1_SX300.jpg|1985|US|

## `director`
|id|name|
|---|---|
|0|Christopher Nolan|
|1|James Wan|

## `movie_director_map`
|movie_id|director_map|
|---|---|
|0|0|
|1|1|

## `actor`
|id|name|
|---|---|
|0|Vera Farmiga|
|1|Ryan Reynolds|

## `movie_actor_map`
|movie_id|actor_id|
|---|---|
|0|0|
|0|1|

## `tag`
|id|type|value|
|---|---|---|
|0|`genre`|판타지|
|1|`genre`|공포|
|2|`country`|한국|
|3|`country`|중국|
|4|`feature`|변신|
|5|`feature`|괴수|

## `movie_tag_map`
|movie_id|tag_id|
|---|---|
|0|0|
|0|1|
|0|1|

## `user`
|id|email|name|password|token|
|---|---|---|---|---|
|1|xxx@naver.com|lee|!@#12232|!@sha33@2
|2|xwe@naver.com|kim|!2343#32|!!@@#sd2
|3|sdx@naver.com|choi|!@$%#$32|@#$#a33@2
|4|cvb@naver.com|kim|4@#$32|~!@a33@2
|5|asz@naver.com|lee|!3#$232|&^%a33@2

## `email_change`
|token|user_id|email|
|---|---|---|
|!@#!!@#123|1|xxx@naver.com|
|59348590873|2|xwe@naver.com|
|uf8eur@#|3|sdx@naver.com|

##  `keyword_movie_map`
|keyword|movie_id|
|---|---|
|Christopher|0|
|Nolan|0|

**Comment by youmustgo** [comment]
## `tag`
|id|type|value|
|---|---|---|
|0|genre|판타지|
|1|genre|공포|
|2|country|한국|
|3|country|중국|
|4|feature|변신|
|5|feature|괴수|

**Comment by dhlee128** [comment]
## Database Schema

### 영화
```
CREATE TABLE `movie` (
    `id` BIGINT AUTO_INCREMENT,
    `title` VARCHAR(100) NOT NULL,
    `description` VARCHAR(3000) NOT NULL,
    `rating` VARCHAR(10) NOT NULL,
    `duration` INT(4) NOT NULL,
    `thumbnail` VARCHAR(2000) NOT NULL,
    `year` INT(4) NOT NULL,
    `country` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`id`)
);
```

### 감독
```
CREATE TABLE `director` (
    `id` BIGINT AUTO_INCREMENT,
    `value` VARCHAR(200) NOT NULL,
    PRIMARY KEY (`id`)
);
```

### 영화 <> 감독 map
```
CREATE TABLE `movie_director_map` (
    `movie_id` BIGINT,
    `director_id` BIGINT,
    PRIMARY KEY (`movie_id`,`director_id`)
);
```

### 배우
```
CREATE TABLE `actor` (
    `id` BIGINT AUTO_INCREMENT,
    `value` VARCHAR(200) NOT NULL,
    PRIMARY KEY (`id`)
);
```

### 영화 <> 배우 map
```
CREATE TABLE `movie_actor_map` (
    `movie_id` BIGINT,
    `actor_id` BIGINT,
    PRIMARY KEY (`movie_id`,`actor_id`)
);
```

### 태그
```
CREATE TABLE `tag` (
    `id` BIGINT AUTO_INCREMENT,
    `type` VARCHAR(10) NOT NULL,
    `value` VARCHAR(200) NOT NULL,
    PRIMARY KEY (`id`)
);
```

### 영화 <> 태그 map
```
CREATE TABLE `movie_tag_map` (
    `movie_id` BIGINT,
    `tag_id` BIGINT,
    PRIMARY KEY (`movie_id`,`tag_id`)
);
```

### 사용자
```
CREATE TABLE `user` (
`id` BIGINT AUTO_INCREMENT,
`email` VARCHAR(100) NOT NULL,
`name` VARCHAR(25) NOT NULL,
`password` VARCHAR(100) NOT NULL,
`token` VARCHAR(100),
`refresh_token` VARCHAR(100),
PRIMARY KEY (`id`),
INDEX(`token`),
INDEX(`refresh_token`),
UNIQUE INDEX  (`email`)
);
```

### 키워드 <> 영화 map
```
CREATE TABLE `keyword_movie_map` (
    `keyword` VARCHAR(100) NOT NULL,
    `movie_id` BIGINT,
    INDEX  (`keyword`, `movie_id`)
);
```

### `email_change`
```
CREATE TABLE `email_change` (
    `token` VARCHAR(100) NOT NULL,
    `user_id` BIGINT,
    `email` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`token`)
);
```

**Comment by dhlee128** [comment]
-- 사용자
CREATE TABLE user (
email VARCHAR(100) NOT NULL,
name VARCHAR(25) NOT NULL,
password VARCHAR(100) NOT NULL,
token VARCHAR(100),
PRIMARY KEY (email)
);
